export type ScotPositionKey = "forward" | "midfielder" | "defender";

export interface ScotSquadPlayer {
  name: string;
  team: string;
  position: ScotPositionKey;
}

/** Full Scottish Premiership outfield squads (2026-27), supplied by the admin as a
 * spreadsheet — goalkeepers are excluded since they're never a pickable position here.
 * TheSportsDB's free-tier squad endpoint only returned a top-10-ish shortlist per club,
 * so this replaces that sync entirely rather than supplementing it. */
export const SCOT_SQUADS: ScotSquadPlayer[] = [
  { name: 'Alexander Briedl', team: 'Aberdeen', position: 'defender' },
  { name: 'Daniel Happe', team: 'Aberdeen', position: 'defender' },
  { name: 'Gavin Molloy', team: 'Aberdeen', position: 'defender' },
  { name: 'Jack Milne', team: 'Aberdeen', position: 'defender' },
  { name: 'Jamie Mercer', team: 'Aberdeen', position: 'defender' },
  { name: 'Kristers Tobers', team: 'Aberdeen', position: 'defender' },
  { name: 'Lewis Mayo', team: 'Aberdeen', position: 'defender' },
  { name: 'Mats Knoester', team: 'Aberdeen', position: 'defender' },
  { name: 'Mitchel Frame', team: 'Aberdeen', position: 'defender' },
  { name: 'Nicky Devlin', team: 'Aberdeen', position: 'defender' },
  { name: 'Ayoub Mouloua', team: 'Aberdeen', position: 'forward' },
  { name: 'Emmanuel Gyamfi', team: 'Aberdeen', position: 'forward' },
  { name: 'Kevin Nisbet', team: 'Aberdeen', position: 'forward' },
  { name: 'Kusini Yengi', team: 'Aberdeen', position: 'forward' },
  { name: 'Marko Lazetic', team: 'Aberdeen', position: 'forward' },
  { name: 'Nicolas Milanovic', team: 'Aberdeen', position: 'forward' },
  { name: 'Peter Ambrose', team: 'Aberdeen', position: 'forward' },
  { name: 'Topi Keskinen', team: 'Aberdeen', position: 'forward' },
  { name: 'Toyosi Olusanya', team: 'Aberdeen', position: 'forward' },
  { name: 'Alexander Jensen', team: 'Aberdeen', position: 'midfielder' },
  { name: 'Alfie Stewart', team: 'Aberdeen', position: 'midfielder' },
  { name: 'Ante Palaversa', team: 'Aberdeen', position: 'midfielder' },
  { name: 'Aremu Afeez', team: 'Aberdeen', position: 'midfielder' },
  { name: 'Brad Lyons', team: 'Aberdeen', position: 'midfielder' },
  { name: 'Connor Ronan', team: 'Aberdeen', position: 'midfielder' },
  { name: 'Dylan Lobban', team: 'Aberdeen', position: 'midfielder' },
  { name: 'Findlay Marshall', team: 'Aberdeen', position: 'midfielder' },
  { name: 'Kenan Bilalovic', team: 'Aberdeen', position: 'midfielder' },
  { name: 'Kjartan Kjartansson', team: 'Aberdeen', position: 'midfielder' },
  { name: 'Stuart Armstrong', team: 'Aberdeen', position: 'midfielder' },
  { name: 'Tony Yogane', team: 'Aberdeen', position: 'midfielder' },
  { name: 'Adam Montgomery', team: 'Celtic', position: 'defender' },
  { name: 'Alistair Johnston', team: 'Celtic', position: 'defender' },
  { name: 'Anthony Ralston', team: 'Celtic', position: 'defender' },
  { name: 'Auston Trusty', team: 'Celtic', position: 'defender' },
  { name: 'Cameron Carter-Vickers', team: 'Celtic', position: 'defender' },
  { name: 'Colby Donovan', team: 'Celtic', position: 'defender' },
  { name: 'Dane Murray', team: 'Celtic', position: 'defender' },
  { name: 'Kieran Tierney', team: 'Celtic', position: 'defender' },
  { name: 'Liam Scales', team: 'Celtic', position: 'defender' },
  { name: 'Maik Nawrocki', team: 'Celtic', position: 'defender' },
  { name: 'Samuel Isiguzo', team: 'Celtic', position: 'defender' },
  { name: 'Benjamin Nygren', team: 'Celtic', position: 'forward' },
  { name: 'Callum Osmand', team: 'Celtic', position: 'forward' },
  { name: 'Daizen Maeda', team: 'Celtic', position: 'forward' },
  { name: 'Johnny Kenny', team: 'Celtic', position: 'forward' },
  { name: 'Jota', team: 'Celtic', position: 'forward' },
  { name: 'Kelechi Iheanacho', team: 'Celtic', position: 'forward' },
  { name: 'Michel-Ange Balikwisha', team: 'Celtic', position: 'forward' },
  { name: 'Sebastian Tounekti', team: 'Celtic', position: 'forward' },
  { name: 'Shin Yamada', team: 'Celtic', position: 'forward' },
  { name: 'Yang Hyun-Jun', team: 'Celtic', position: 'forward' },
  { name: 'Alex Oxlade-Chamberlain', team: 'Celtic', position: 'midfielder' },
  { name: 'Arne Engels', team: 'Celtic', position: 'midfielder' },
  { name: 'Callum McGregor', team: 'Celtic', position: 'midfielder' },
  { name: 'Finlay Hale', team: 'Celtic', position: 'midfielder' },
  { name: 'James Forrest', team: 'Celtic', position: 'midfielder' },
  { name: 'Joseph Haney', team: 'Celtic', position: 'midfielder' },
  { name: 'Kyle Ure', team: 'Celtic', position: 'midfielder' },
  { name: 'Luke McCowan', team: 'Celtic', position: 'midfielder' },
  { name: 'Paulo Bernardo', team: 'Celtic', position: 'midfielder' },
  { name: 'Reo Hatate', team: 'Celtic', position: 'midfielder' },
  { name: 'Sean Mcardle', team: 'Celtic', position: 'midfielder' },
  { name: 'Thomas Hatton', team: 'Celtic', position: 'midfielder' },
  { name: 'Aaron Donnelly', team: 'Dundee', position: 'defender' },
  { name: 'Billy Koumetio', team: 'Dundee', position: 'defender' },
  { name: 'Clark Robertson', team: 'Dundee', position: 'defender' },
  { name: 'Drey Wright', team: 'Dundee', position: 'defender' },
  { name: 'Imari Samuels', team: 'Dundee', position: 'defender' },
  { name: 'Lewis Montsma', team: 'Dundee', position: 'defender' },
  { name: 'Luke Graham', team: 'Dundee', position: 'defender' },
  { name: 'Ryan Astley', team: 'Dundee', position: 'defender' },
  { name: 'Ashley Hay', team: 'Dundee', position: 'forward' },
  { name: 'Cameron Congreve', team: 'Dundee', position: 'forward' },
  { name: 'Finlay Allan', team: 'Dundee', position: 'forward' },
  { name: 'Francisco Valenzuela', team: 'Dundee', position: 'forward' },
  { name: 'Joe Bevan', team: 'Dundee', position: 'forward' },
  { name: 'Joe Westley', team: 'Dundee', position: 'forward' },
  { name: 'Scott Wright', team: 'Dundee', position: 'forward' },
  { name: 'Simon Murray', team: 'Dundee', position: 'forward' },
  { name: 'Tony Yogane', team: 'Dundee', position: 'forward' },
  { name: 'Bradley Halliday', team: 'Dundee', position: 'midfielder' },
  { name: 'Callum Jones', team: 'Dundee', position: 'midfielder' },
  { name: 'Charlie Reilly', team: 'Dundee', position: 'midfielder' },
  { name: 'Ethan Crombie', team: 'Dundee', position: 'midfielder' },
  { name: 'Ethan Hamilton', team: 'Dundee', position: 'midfielder' },
  { name: 'Finlay Robertson', team: 'Dundee', position: 'midfielder' },
  { name: 'Joel Cotterill', team: 'Dundee', position: 'midfielder' },
  { name: 'Paul Digby', team: 'Dundee', position: 'midfielder' },
  { name: 'Yan Dhanda', team: 'Dundee', position: 'midfielder' },
  { name: 'Bert Esselink', team: 'Dundee United', position: 'defender' },
  { name: 'Harry Welsh', team: 'Dundee United', position: 'defender' },
  { name: 'Iurie Iovu', team: 'Dundee United', position: 'defender' },
  { name: 'Matthew Mudie', team: 'Dundee United', position: 'defender' },
  { name: 'Michael Forbes', team: 'Dundee United', position: 'defender' },
  { name: 'Ross Graham', team: 'Dundee United', position: 'defender' },
  { name: 'Sam Cleall-Harding', team: 'Dundee United', position: 'defender' },
  { name: 'Scott Constable', team: 'Dundee United', position: 'defender' },
  { name: 'Ivan Dolcek', team: 'Dundee United', position: 'forward' },
  { name: 'Johnny Russell', team: 'Dundee United', position: 'forward' },
  { name: 'Kristijan Trapanovski', team: 'Dundee United', position: 'forward' },
  { name: 'Max Watters', team: 'Dundee United', position: 'forward' },
  { name: 'Owen Stirton', team: 'Dundee United', position: 'forward' },
  { name: 'Zachary Sapsford', team: 'Dundee United', position: 'forward' },
  { name: 'Calvin Beattie', team: 'Dundee United', position: 'midfielder' },
  { name: 'Craig Sibbald', team: 'Dundee United', position: 'midfielder' },
  { name: 'Dario Naamo', team: 'Dundee United', position: 'midfielder' },
  { name: 'Dylan Tait', team: 'Dundee United', position: 'midfielder' },
  { name: 'Emmanuel Agyei', team: 'Dundee United', position: 'midfielder' },
  { name: 'Jack Anderson', team: 'Dundee United', position: 'midfielder' },
  { name: 'Julius Eskesen', team: 'Dundee United', position: 'midfielder' },
  { name: 'Keir Gilligan', team: 'Dundee United', position: 'midfielder' },
  { name: 'Miller Thomson', team: 'Dundee United', position: 'midfielder' },
  { name: 'Neil Farrugia', team: 'Dundee United', position: 'midfielder' },
  { name: 'Panutche Camara', team: 'Dundee United', position: 'midfielder' },
  { name: 'Ryan Strain', team: 'Dundee United', position: 'midfielder' },
  { name: 'Vicko Sevelj', team: 'Dundee United', position: 'midfielder' },
  { name: 'Will Ferry', team: 'Dundee United', position: 'midfielder' },
  { name: 'Coll Donaldson', team: 'Falkirk', position: 'defender' },
  { name: 'Connor Allan', team: 'Falkirk', position: 'defender' },
  { name: 'Deniss Melniks', team: 'Falkirk', position: 'defender' },
  { name: 'Filip Lissah', team: 'Falkirk', position: 'defender' },
  { name: 'Keelan Adams', team: 'Falkirk', position: 'defender' },
  { name: 'Leon McCann', team: 'Falkirk', position: 'defender' },
  { name: 'Liam Henderson', team: 'Falkirk', position: 'defender' },
  { name: 'Sam Hart', team: 'Falkirk', position: 'defender' },
  { name: 'Thomas Lang', team: 'Falkirk', position: 'defender' },
  { name: 'Alfie Agyeman', team: 'Falkirk', position: 'forward' },
  { name: 'Ben Broggio', team: 'Falkirk', position: 'forward' },
  { name: 'Ben Parkinson', team: 'Falkirk', position: 'forward' },
  { name: 'Brian Graham', team: 'Falkirk', position: 'forward' },
  { name: 'Ethan Ross', team: 'Falkirk', position: 'forward' },
  { name: 'Gary Oliver', team: 'Falkirk', position: 'forward' },
  { name: 'Paul McGovern', team: 'Falkirk', position: 'forward' },
  { name: 'Ross MacIver', team: 'Falkirk', position: 'forward' },
  { name: 'Aidan Nesbitt', team: 'Falkirk', position: 'midfielder' },
  { name: 'Brad Spencer', team: 'Falkirk', position: 'midfielder' },
  { name: 'Finn Yeats', team: 'Falkirk', position: 'midfielder' },
  { name: 'Henry Cartwright', team: 'Falkirk', position: 'midfielder' },
  { name: 'Kalvin Bennett', team: 'Falkirk', position: 'midfielder' },
  { name: 'Scott Tanser', team: 'Falkirk', position: 'midfielder' },
  { name: 'Sean Mackie', team: 'Falkirk', position: 'midfielder' },
  { name: 'Christian Borchgrevink', team: 'Heart of Midlothian', position: 'defender' },
  { name: 'Craig Halkett', team: 'Heart of Midlothian', position: 'defender' },
  { name: 'Euan Glasgow', team: 'Heart of Midlothian', position: 'defender' },
  { name: 'Harry Milne', team: 'Heart of Midlothian', position: 'defender' },
  { name: 'Jamie McCart', team: 'Heart of Midlothian', position: 'defender' },
  { name: 'Jordi Altena', team: 'Heart of Midlothian', position: 'defender' },
  { name: 'Malachi Fagan-Walcott', team: 'Heart of Midlothian', position: 'defender' },
  { name: 'Michael John Kamara', team: 'Heart of Midlothian', position: 'defender' },
  { name: 'Oisin McEntee', team: 'Heart of Midlothian', position: 'defender' },
  { name: 'Stephen Kingsley', team: 'Heart of Midlothian', position: 'defender' },
  { name: 'Stuart Findlay', team: 'Heart of Midlothian', position: 'defender' },
  { name: 'Amadou Ba-Sy', team: 'Heart of Midlothian', position: 'forward' },
  { name: 'Cláudio Braga', team: 'Heart of Midlothian', position: 'forward' },
  { name: 'Connor Dow', team: 'Heart of Midlothian', position: 'forward' },
  { name: 'Elton Kabangu', team: 'Heart of Midlothian', position: 'forward' },
  { name: 'Finlay Pollock', team: 'Heart of Midlothian', position: 'forward' },
  { name: 'James Wilson', team: 'Heart of Midlothian', position: 'forward' },
  { name: 'Jayden Mathie', team: 'Heart of Midlothian', position: 'forward' },
  { name: 'Pierre Landry Kaboré', team: 'Heart of Midlothian', position: 'forward' },
  { name: 'Rogers Mato', team: 'Heart of Midlothian', position: 'forward' },
  { name: 'Sabah Kerjota', team: 'Heart of Midlothian', position: 'forward' },
  { name: 'Severin Sabri Guendouz', team: 'Heart of Midlothian', position: 'forward' },
  { name: 'Ageu', team: 'Heart of Midlothian', position: 'midfielder' },
  { name: 'Alexandros Kyziridis', team: 'Heart of Midlothian', position: 'midfielder' },
  { name: 'Blair Spittal', team: 'Heart of Midlothian', position: 'midfielder' },
  { name: 'Calvin Miller', team: 'Heart of Midlothian', position: 'midfielder' },
  { name: 'Josh McPake', team: 'Heart of Midlothian', position: 'midfielder' },
  { name: 'Laurent Mendy', team: 'Heart of Midlothian', position: 'midfielder' },
  { name: 'Sander Erik Kartum', team: 'Heart of Midlothian', position: 'midfielder' },
  { name: 'Stanley Wilson', team: 'Heart of Midlothian', position: 'midfielder' },
  { name: 'Tom Renaud', team: 'Heart of Midlothian', position: 'midfielder' },
  { name: 'Tomas Magnusson', team: 'Heart of Midlothian', position: 'midfielder' },
  { name: 'Yan Dhanda', team: 'Heart of Midlothian', position: 'midfielder' },
  { name: 'Grant Hanley', team: 'Hibernian', position: 'defender' },
  { name: 'Jack Iredale', team: 'Hibernian', position: 'defender' },
  { name: 'Jason Kerr', team: 'Hibernian', position: 'defender' },
  { name: 'Jordan Obita', team: 'Hibernian', position: 'defender' },
  { name: 'Rocky Bushiri', team: 'Hibernian', position: 'defender' },
  { name: 'Rudi Allan Molotnikov', team: 'Hibernian', position: 'defender' },
  { name: 'Warren O\'Hora', team: 'Hibernian', position: 'defender' },
  { name: 'Adam Mayor', team: 'Hibernian', position: 'forward' },
  { name: 'Ante Suto', team: 'Hibernian', position: 'forward' },
  { name: 'Jacob MacIntyre', team: 'Hibernian', position: 'forward' },
  { name: 'Martin Boyle', team: 'Hibernian', position: 'forward' },
  { name: 'Nathan Lowe', team: 'Hibernian', position: 'forward' },
  { name: 'Owen Elding', team: 'Hibernian', position: 'forward' },
  { name: 'Thibault Klidje', team: 'Hibernian', position: 'forward' },
  { name: 'Alasana Manneh', team: 'Hibernian', position: 'midfielder' },
  { name: 'Azeem Abdulai', team: 'Hibernian', position: 'midfielder' },
  { name: 'Callum Wright', team: 'Hibernian', position: 'midfielder' },
  { name: 'Chris Cadden', team: 'Hibernian', position: 'midfielder' },
  { name: 'Felix Passlack', team: 'Hibernian', position: 'midfielder' },
  { name: 'Jamie McGrath', team: 'Hibernian', position: 'midfielder' },
  { name: 'Joe Newell', team: 'Hibernian', position: 'midfielder' },
  { name: 'Josh Campbell', team: 'Hibernian', position: 'midfielder' },
  { name: 'Josh Mulligan', team: 'Hibernian', position: 'midfielder' },
  { name: 'Kanayochukwu Megwa', team: 'Hibernian', position: 'midfielder' },
  { name: 'Miguel Chaiwa', team: 'Hibernian', position: 'midfielder' },
  { name: 'Nicky Cadden', team: 'Hibernian', position: 'midfielder' },
  { name: 'Dominic Thompson', team: 'Kilmarnock', position: 'defender' },
  { name: 'Ethan Schilte-Brown', team: 'Kilmarnock', position: 'defender' },
  { name: 'George Stanger', team: 'Kilmarnock', position: 'defender' },
  { name: 'Jamie Brandon', team: 'Kilmarnock', position: 'defender' },
  { name: 'Lewis Mayo', team: 'Kilmarnock', position: 'defender' },
  { name: 'Michael Schjonning-Larsen', team: 'Kilmarnock', position: 'defender' },
  { name: 'Robbie Deas', team: 'Kilmarnock', position: 'defender' },
  { name: 'Zac Williams', team: 'Kilmarnock', position: 'defender' },
  { name: 'Bruce Anderson', team: 'Kilmarnock', position: 'forward' },
  { name: 'Djenairo Daniels', team: 'Kilmarnock', position: 'forward' },
  { name: 'Joe Hugill', team: 'Kilmarnock', position: 'forward' },
  { name: 'Kian Leslie', team: 'Kilmarnock', position: 'forward' },
  { name: 'Marcus Dackers', team: 'Kilmarnock', position: 'forward' },
  { name: 'Marley Watkins', team: 'Kilmarnock', position: 'forward' },
  { name: 'Nicky Clescenco', team: 'Kilmarnock', position: 'forward' },
  { name: 'Scott Tiffoney', team: 'Kilmarnock', position: 'forward' },
  { name: 'Tyreece John-Jules', team: 'Kilmarnock', position: 'forward' },
  { name: 'Aaron Davis', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'Aaron Tshibola', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'Brad Lyons', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'Cole Coughlin', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'David Watson', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'Findlay Curtis', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'Greg Kiltie', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'Jack Thomson', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'James Brown', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'Kyle Magennis', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'Liam Polworth', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'Matthew Kennedy', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'Rory McKenzie', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'Tom Lowery', team: 'Kilmarnock', position: 'midfielder' },
  { name: 'Emmanuel Longelo', team: 'Motherwell', position: 'defender' },
  { name: 'Johnny Koutroumbis', team: 'Motherwell', position: 'defender' },
  { name: 'Jordan McGhee', team: 'Motherwell', position: 'defender' },
  { name: 'Liam Gordon', team: 'Motherwell', position: 'defender' },
  { name: 'Paul McGinn', team: 'Motherwell', position: 'defender' },
  { name: 'Sam Nicholson', team: 'Motherwell', position: 'defender' },
  { name: 'Stephen O\'Donnell', team: 'Motherwell', position: 'defender' },
  { name: 'Stephen Welsh', team: 'Motherwell', position: 'defender' },
  { name: 'Apostolos Stamatelopoulos', team: 'Motherwell', position: 'forward' },
  { name: 'Callum Hendry', team: 'Motherwell', position: 'forward' },
  { name: 'Eseosa Sule', team: 'Motherwell', position: 'forward' },
  { name: 'Eythor Martin Bjorgolfsson', team: 'Motherwell', position: 'forward' },
  { name: 'Ibrahim Said', team: 'Motherwell', position: 'forward' },
  { name: 'Luca Ross', team: 'Motherwell', position: 'forward' },
  { name: 'Regan Charles-Cook', team: 'Motherwell', position: 'forward' },
  { name: 'Tawanda Maswanhise', team: 'Motherwell', position: 'forward' },
  { name: 'Zach Robinson', team: 'Motherwell', position: 'forward' },
  { name: 'Aaron Thomson', team: 'Motherwell', position: 'midfielder' },
  { name: 'Andrew Halliday', team: 'Motherwell', position: 'midfielder' },
  { name: 'Callum Slattery', team: 'Motherwell', position: 'midfielder' },
  { name: 'Elijah Just', team: 'Motherwell', position: 'midfielder' },
  { name: 'Elliot Watt', team: 'Motherwell', position: 'midfielder' },
  { name: 'Lukas Fadinger', team: 'Motherwell', position: 'midfielder' },
  { name: 'Oscar Priestman', team: 'Motherwell', position: 'midfielder' },
  { name: 'Tom Sparrow', team: 'Motherwell', position: 'midfielder' },
  { name: 'Arran Kerr', team: 'Rangers', position: 'defender' },
  { name: 'Ashton Scally', team: 'Rangers', position: 'defender' },
  { name: 'Ben Godfrey', team: 'Rangers', position: 'defender' },
  { name: 'Calum Adamson', team: 'Rangers', position: 'defender' },
  { name: 'Clinton Nsiala-Makengo', team: 'Rangers', position: 'defender' },
  { name: 'Dujon Sterling', team: 'Rangers', position: 'defender' },
  { name: 'Emmanuel Fernandez', team: 'Rangers', position: 'defender' },
  { name: 'John Souttar', team: 'Rangers', position: 'defender' },
  { name: 'Leon Thomson King', team: 'Rangers', position: 'defender' },
  { name: 'Ross McCrorie', team: 'Rangers', position: 'defender' },
  { name: 'Tuur Rommens', team: 'Rangers', position: 'defender' },
  { name: 'Bojan Miovski', team: 'Rangers', position: 'forward' },
  { name: 'Danilo', team: 'Rangers', position: 'forward' },
  { name: 'Djeidi Gassama', team: 'Rangers', position: 'forward' },
  { name: 'Findlay Curtis', team: 'Rangers', position: 'forward' },
  { name: 'Lawrence Shankland', team: 'Rangers', position: 'forward' },
  { name: 'Lewis Stewart', team: 'Rangers', position: 'forward' },
  { name: 'Oliver Antman', team: 'Rangers', position: 'forward' },
  { name: 'Ryan Naderi', team: 'Rangers', position: 'forward' },
  { name: 'Youssef Chermiti', team: 'Rangers', position: 'forward' },
  { name: 'Zebedee Lawson', team: 'Rangers', position: 'forward' },
  { name: 'Aiden Mccallion', team: 'Rangers', position: 'midfielder' },
  { name: 'Alexander Smith', team: 'Rangers', position: 'midfielder' },
  { name: 'Bailey Rice', team: 'Rangers', position: 'midfielder' },
  { name: 'Connor Barron', team: 'Rangers', position: 'midfielder' },
  { name: 'Daniel Neil', team: 'Rangers', position: 'midfielder' },
  { name: 'José Cifuentes', team: 'Rangers', position: 'midfielder' },
  { name: 'Lyall Cameron', team: 'Rangers', position: 'midfielder' },
  { name: 'Mohammed Diomande', team: 'Rangers', position: 'midfielder' },
  { name: 'Nedim Bajrami', team: 'Rangers', position: 'midfielder' },
  { name: 'Nicolas Raskin', team: 'Rangers', position: 'midfielder' },
  { name: 'Ross McCausland', team: 'Rangers', position: 'midfielder' },
  { name: 'Thelo Aasgaard', team: 'Rangers', position: 'midfielder' },
  { name: 'Tochi Phil Chukwuani', team: 'Rangers', position: 'midfielder' },
  { name: 'Adam Forrester', team: 'St Johnstone', position: 'defender' },
  { name: 'Bozo Mikulic', team: 'St Johnstone', position: 'defender' },
  { name: 'Cheick Diabate', team: 'St Johnstone', position: 'defender' },
  { name: 'Jack Baird', team: 'St Johnstone', position: 'defender' },
  { name: 'Liam Smith', team: 'St Johnstone', position: 'defender' },
  { name: 'Matty Foulds', team: 'St Johnstone', position: 'defender' },
  { name: 'Morgan Boyes', team: 'St Johnstone', position: 'defender' },
  { name: 'Reghan Tumilty', team: 'St Johnstone', position: 'defender' },
  { name: 'Sam McClelland', team: 'St Johnstone', position: 'defender' },
  { name: 'Alfie Agyeman', team: 'St Johnstone', position: 'forward' },
  { name: 'Jamie Gullan', team: 'St Johnstone', position: 'forward' },
  { name: 'Josh Fowler', team: 'St Johnstone', position: 'forward' },
  { name: 'Joshua McPake', team: 'St Johnstone', position: 'forward' },
  { name: 'Kai Fotheringham', team: 'St Johnstone', position: 'forward' },
  { name: 'Louis Lloyd', team: 'St Johnstone', position: 'forward' },
  { name: 'Ruari Paton', team: 'St Johnstone', position: 'forward' },
  { name: 'Stephen Mallan', team: 'St Johnstone', position: 'forward' },
  { name: 'Taylor Steven', team: 'St Johnstone', position: 'forward' },
  { name: 'Franciszek Franczak', team: 'St Johnstone', position: 'midfielder' },
  { name: 'Jason Holt', team: 'St Johnstone', position: 'midfielder' },
  { name: 'Jonathan Svedberg', team: 'St Johnstone', position: 'midfielder' },
  { name: 'Reece McAlear', team: 'St Johnstone', position: 'midfielder' },
  { name: 'Samuel Stanton', team: 'St Johnstone', position: 'midfielder' },
  { name: 'Alexandros Gogic', team: 'St Mirren', position: 'defender' },
  { name: 'Jalmaro Calvin', team: 'St Mirren', position: 'defender' },
  { name: 'Marcus Fraser', team: 'St Mirren', position: 'defender' },
  { name: 'Miguel Freckleton', team: 'St Mirren', position: 'defender' },
  { name: 'Richard King', team: 'St Mirren', position: 'defender' },
  { name: 'Tunmise Sobowale', team: 'St Mirren', position: 'defender' },
  { name: 'Dan Nlundulu', team: 'St Mirren', position: 'forward' },
  { name: 'Jake Young', team: 'St Mirren', position: 'forward' },
  { name: 'Jonah Ayunga', team: 'St Mirren', position: 'forward' },
  { name: 'Kion Etete', team: 'St Mirren', position: 'forward' },
  { name: 'Mikael Mandron', team: 'St Mirren', position: 'forward' },
  { name: 'Roland Idowu', team: 'St Mirren', position: 'forward' },
  { name: 'Allan Campbell', team: 'St Mirren', position: 'midfielder' },
  { name: 'Conor McMenamin', team: 'St Mirren', position: 'midfielder' },
  { name: 'Declan John', team: 'St Mirren', position: 'midfielder' },
  { name: 'Jacob Devaney', team: 'St Mirren', position: 'midfielder' },
  { name: 'Jayden Richardson', team: 'St Mirren', position: 'midfielder' },
  { name: 'Keanu Baccus', team: 'St Mirren', position: 'midfielder' },
  { name: 'Killian Phillips', team: 'St Mirren', position: 'midfielder' },
  { name: 'Liam Donnelly', team: 'St Mirren', position: 'midfielder' },
  { name: 'Malik Dijksteel', team: 'St Mirren', position: 'midfielder' },
  { name: 'Mark O\'Hara', team: 'St Mirren', position: 'midfielder' },
  { name: 'Scott Tanser', team: 'St Mirren', position: 'midfielder' },
];
